version: '2'
services:
  homeassistant:
    build: .
    container_name: home-assistant
    image: homeassistant/home-assistant
    volumes:
      - /root/homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: always
    network_mode: host
